tensorlayer/hyperpose

config.py, inference.py, models.py, setup.cfg, train.py, utils.py
https://github.com/tensorlayer/openpose/issues/10
=> [pls merge] Update config.py #10

.gitignore, inference/common.py, inference/estimator2.py, inference/export.py, inference/models.py, inference/run.py, inference/test_inference-2.py, inference/test_inference.py, scripts/.gitignore, scripts/freeze-graph.sh
This is part of #18, cherrypicked as a separate PR so it could be merged into master earlier (The C++ part needs more cleaning).
@zsdonghao @boldjoel please make sure it won't break your work.
=> export model for serving

.gitignore, README.md, config.py, models.py, models_mobilenet.py, models_vgg.py
* release mobilenet model
* readme
* split two models
* cleanup
=> release mobilenet model (#35)

.travis.yml, export.py, models.py, models_mobilenet.py, scripts/freeze-graph.sh, test_inference.py
* fix bug
* test mobilenet
* refactor export.py
* fix
=> fix bug (#38)

src/paf.cpp, src/paf.h, src/pose_detector.cpp, src/uff-runner.cpp, src/uff-runner.h
* rename variables
* UFFRunner -> uff_runner
* maxBatchSize -> max_batch_size
* minor renaming
=> merge master

.travis.yml, docker/Dockerfile.builder-cpu-ubuntu18, docker/Dockerfile.travis-ci, docker/Makefile
=> Make CI faster

CMakeLists.txt, cmake/3rdparty.cmake, cmake/examples.cmake, cmake/openpose-plus.cmake
A quick for #138, tested with cmake 10 and 12 on ubuntu18.
=> a simple fix for cmake (#138)

.travis.yml
https://github.com/tensorlayer/NIPS_Workshop/issues/4
=> run hao28 with real data

doc/markdown-doc/cpp-inference.md, src/post_process.hpp
=> Fix core dump

cmake/3rdparty.cmake, examples/thread_pool.cpp
=> compatibility fix

.readthedocs.yml, .travis.yml
built: https://readthedocs.org/projects/openpose-plus/builds/11155121/
=> fix master doc build

docs/requirements.txt
built: https://readthedocs.org/projects/hyperpose/builds/11198113/
=> fix doc build

Hyperpose/Config/__init__.py, Hyperpose/Dataset/__init__.py, Hyperpose/Model/common.py, Hyperpose/Model/openpose/eval.py, Hyperpose/Model/openpose/train.py, Hyperpose/Model/pose_proposal/eval.py, Hyperpose/Model/pose_proposal/infer.py, Hyperpose/Model/pose_proposal/model.py, Hyperpose/Model/pose_proposal/train.py, docs/markdown/tutorial/training.md, train.py
2.learning rate, batch size, dataset API added and tested
=> 1.parallel traning tested and debugged, with document modified

src/tensorrt.cpp
The PR https://github.com/tensorlayer/hyperpose/pull/282 introduced the reuse optimization of tensorrt context. however, coupled with a segmentation fault bug.
The change is verified to solve the segmentation fault in my Ubuntu 18.04 PC.
=> Fix Segmentation fault

README.md
https://hub.docker.com/r/tensorlayer/hyperpose
=> Fix Docker Badge link.

src/paf.cpp
Thanks to:
https://github.com/tensorlayer/hyperpose/issues/318#issuecomment-705751006
=> Fix index out of range error

README.md, hyperpose/Config/__init__.py, hyperpose/Config/config_pifpaf.py, hyperpose/Config/define.py, hyperpose/Dataset/__init__.py, hyperpose/Dataset/mscoco_dataset/dataset.py, hyperpose/Dataset/mscoco_dataset/define.py, hyperpose/Model/__init__.py, hyperpose/Model/backbones.py, hyperpose/Model/common.py, hyperpose/Model/human.py, hyperpose/Model/metrics.py, hyperpose/Model/openpose/eval.py, hyperpose/Model/openpose/train.py, hyperpose/Model/openpose/utils.py, hyperpose/Model/pifpaf/__init__.py, hyperpose/Model/pifpaf/define.py, hyperpose/Model/pifpaf/eval.py, hyperpose/Model/pifpaf/infer.py, hyperpose/Model/pifpaf/model.py, hyperpose/Model/pifpaf/train.py, hyperpose/Model/pifpaf/utils.py, hyperpose/Model/pose_proposal/eval.py, hyperpose/Model/pose_proposal/utils.py, requirements.txt, train.py
Pifpaf Added!
1.Training process
2.Evaluating process
=> [New Algorithm Support] PifPaf

hyperpose/Dataset/base_dataset.py, hyperpose/Model/augmentor.py, hyperpose/Model/openpose/train.py, hyperpose/Model/pifpaf/model.py, hyperpose/Model/pose_proposal/eval.py, hyperpose/Model/pose_proposal/processor.py, hyperpose/Model/pose_proposal/train.py, hyperpose/Model/pose_proposal/utils.py
pre/post processors of each model integrated and debuged
=> Processor Integration

export_pb.py, hyperpose/Config/config_pifpaf.py, hyperpose/Dataset/mscoco_dataset/dataset.py, hyperpose/Model/__init__.py, hyperpose/Model/openpose/__init__.py, hyperpose/Model/pifpaf/__init__.py, hyperpose/Model/pifpaf/model.py, hyperpose/Model/pifpaf/processor.py, hyperpose/Model/pifpaf/train.py, hyperpose/Model/pifpaf/utils.py, hyperpose/Model/pose_proposal/__init__.py, infer.py, measure_flops.py, official_test.py
I.Pifpaf accuracy debugging 
1.Use same loss weight configuration with original repo
2.Use same optimizer with original repo(SGD with nestrov)
3.Use same pretrain backbone(converted from original repo)
4.Use weight-decay in training
II.Model deployment complexity measurement added
1.measure_flops.py allows to measure GFlops of converted model in pb format
=> Pifpaf accuracy debug and model complexity deployment

.gitignore, export_tflite.py, hyperpose/Model/backbones.py, hyperpose/Model/common.py, hyperpose/Model/pifpaf/eval.py, hyperpose/Model/pifpaf/model.py, hyperpose/Model/pifpaf/processor.py, hyperpose/Model/pifpaf/train.py, hyperpose/Model/pifpaf/utils.py, setup.py
(I)Pifpaf Accuracy debug:
(1)pixel shuffle reimplemented
(2)input data normalized by mean and std
(3)resnet backbone corrected
(4)output scale activation corrected
(II)Model exportion support
(1)Tflite exportion supported
(III)Pypi setup support
(1)pip install hyperpose python interface supported
=> Pifpaf Accuracy+Model export+Pypi setup

docs/markdown/install/training.md, docs/markdown/quick_start/training.md
=> (I)Documents refinement

README.md, docs/markdown/install/training.md, docs/markdown/quick_start/training.md, docs/markdown/tutorial/training.md, setup.py
(1)sample training program on README.md.
(2)quick start type fixed.
(3)Kungfu installation instructions added.
(4)Setup information fixed.
=> Training documentation fixed.

README.md, docs/markdown/design/design.md, docs/markdown/install/prediction.md, docs/markdown/quick_start/prediction.md
- Tested by grammarly
- Refine some layout stuff to make it more structural and compact
- Refine Python Training code samples to make it shorter @Gyx-One Please have a look here.
Also cc @luomai
=> Improve README

docs/markdown/quick_start/training.md
quick fix of the font size. cc @Gyx-One
=> fix: doc style

docs/markdown/quick_start/training.md, docs/markdown/tutorial/training.md
=> Document Fix:

.gitignore, configure, src/color.hpp
e.g.
```
./configure --examples --tests --user-code && make && make test 
```
=> add back the configure script

README.md
=> update readme regarding citation
